### ISSUE TITLE
Add data from magnetomethers

### ISSUE THREAD

**Issue by uMag** [erdees/AuroraHuntersBot#5]
From Kev
1h data https://space.fmi.fi/image/realtime/UT/KEV/KEVdata_01.txt
24h data https://space.fmi.fi/image/realtime/UT/KEV/KEVdata_24.txt

And tartu one 

https://space.fmi.fi/image/realtime/UT/TAR/TARdata_01.txt
https://space.fmi.fi/image/realtime/UT/TAR/TARdata_24.txt

source page https://space.fmi.fi/image/realtime/UT/

**Comment by ladynoname** [comment]
We need:

KEV, OUJ, HAN and NUR. TAR is don`t needed.

**Comment by uMag** [comment]
Ok, data sources are showed on source page in right column.
And also it makes sense to have separate table for that data

**Comment by erdees** [comment]
@uMag done.
